name: alsham_socialmedia
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  pin_code_fields: ^7.4.0
  iconly: ^1.0.1
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  # platform_device_id: ^1.0.1
  # url_strategy: ^0.2.0
  # shared_preferences: ^2.0.15
  # device_info_plus: ^4.0.1

  # pubnub: ^4.2.2

  # sendbird_sdk: ^3.2.6
  dash_chat_2: ^0.0.15
  socket_io_client: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - assets/
