// class Strings {
//   static const logo = 'assets/images/mash_logo.png';
//   static const location = 'assets/images/location_pin.png';
//   static const male = 'Male';
//   static const female = 'Female';
//   static const List artsList = [
//     'Dancing 💃',
//     'Writing 📝',
//     'Singing 🎤',
//     'Painting 🎨',
//     'Filming 📹',
//     'Photography 📸',
//     'Sculpting 🗿',
//     'Architecture 🏛️',
//     'theater 🎭',
//     'Literature 📚',
//     'Poetry 📜',
//     'Music ♫',
//     'Makeup 💄',
//     'Fashion design 👗',
//     'Standup Comedy 😆',
//   ];
//   static const List sportsList = [
//     'Football ⚽',
//     'Basketball 🏀',
//     'Gymnastics 🤸',
//     'Rock Climbing 🧗🏽‍♀️',
//     'Badminton 🏸',
//     'Tennis 🎾',
//     'Bowling 🎳',
//     'Boxing 🥊',
//     'Cricket 🏏',
//     'Cycling 🚲',
//     'Golf ⛳',
//     'handball',
//     'Horse Riding🐎',
//     'Martial Arts 🥋',
//     'Yoga 🧘',
//     'Meditation ☯',
//     'Pétanque ⚪',
//     'Rugby 🏈',
//     'Skateboarding 🛹',
//     'Skiing 🎿',
//     'Snowboarding 🏂',
//     'Surfing 🏄',
//     'Ping pong 🏓',
//     'Volleyball 🏐',
//     'Squash ⚫',
//     'Billiard 🎱',
//     'Swimming 🏊‍♂️',
//   ];
//   static const List funList = [
//     'Nightclub 🕺🏻',
//     'Cinema🎬🍿',
//     'Comedy Clubs 🎟',
//     'Bars🍻',
//     'Museum 🏺',
//     'Concerts 🎙️ 🎫',
//     'Video Games 🎮',
//     'Board games 🎲',
//     'Cooking 👨🏻‍🍳',
//     'Baking 🍰',
//     'Café ☕',
//     'Festivals 🎆',
//     'Reading 📖',
//     'Movies 📺',
//     'Tv shows 📺',
//     'traveling ✈️',
//     'shopping 🛍️',
//     'Anime',
//   ];
//   static const List valuesList = [
//     'Human rights ✊',
//     'Sustainability 🌎',
//     'Environmentalist ♻️',
//     'Animal Rights 🐘',
//     'LGBTQI rights 🏳️‍🌈',
//     'Black Lives Matter ✊🏿',
//     'Feminism 🙆‍♀️',
//     'Free Speech 🗣️',
//     'Anti-racism ✋🏽 ✋🏿',
//     'Equality for all ⚖️',
//     'antiableism',
//   ];
// }
